runtime:
  catalog: test
  schema: test
  parallel-number: 4

file-connector:
  file.info.student:
    catalog: file
    schema: info
    table: student
    file-type: csv
    column-names: [ id,name,age ]
    column-types: [ INT64,STRING,INT32 ]
    paths: [ ../db/file/info/student/ ]

http-connector:
  http.etcd.*:
    catalog: http
    schema: etcd
    table: "*"
    data-path:
    column-names: [ key, value, _http, _ ]
    column-types: [ STRING, STRING, STRING, STRING ]


mysql-connector:
  mysql.goploy.*:
    catalog: localhost
    schema: goploy
    table: user
    host: 127.0.0.1
    port: 3306
    user: root
    password:
    column-names: []
    column-types: []

etcd:
  endpoint: [ http://127.0.0.1:2379 ]
  dial-timeout: 5
  dial-keepalive-timeout: 5
  username:
  password:

coordinator:
  http-port: 8001

worker:
  ip: 127.0.0.1
  tcp-port: 50051
  rpc-port: 50052
